//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace test.Dal.HelperClasses
{
	/// <summary>Field Creation Class for entity TestEntity</summary>
	public partial class TestFields
	{
		/// <summary>Creates a new TestEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TestFieldIndex.Id); }}
		/// <summary>Creates a new TestEntity.Ma field instance</summary>
		public static EntityField2 Ma { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TestFieldIndex.Ma); }}
		/// <summary>Creates a new TestEntity.Soluong field instance</summary>
		public static EntityField2 Soluong { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TestFieldIndex.Soluong); }}
		/// <summary>Creates a new TestEntity.Ten field instance</summary>
		public static EntityField2 Ten { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TestFieldIndex.Ten); }}
	}
	

}